### ISSUE TITLE
Status of this work item/spec?

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/peer-did-method-spec#42]
Hey @dhh1128 , I've been getting questions about this, and it looks fairly stale, nothing merged in almost a year.  Should we:

1. Add a little "DEPRECATED; WORK MOVED TO https://..." disclaimer across the top;
1. Add a similar disclaimer to the root repo readme file; and
2. Archive the underlying github repo 

Or are there systems in product that use this, which would be slandered by such an archiving?  If so, we should call this v1, wrap it up, officially approve it, and maybe still point to ongoing work if v2 is happening elsewhere, in KERI land, etc.

CC @alenhorvat  @peacekeeper

**Comment by dhh1128** [comment]
IMO, the peer DID method should be superseded by using KERI DIDs in a particular mode that matches peer DID features, AND/OR by the did:key method when there is no need for endpoints or key rotation. The other latent issue with the spec, IMO, is that we need to update minor details in a couple places now that the DID spec has become a TR.

However, there is no impediment to using this DID method today. There are libraries for it in several programming languages, and they work well. So I don't think it's vital that we give the method a deprecated status. It's just old, not bad.

I don't mind merging (and that means writing, I suppose) a PR that inserts a note to that effect at the top of the document. I've not do so, to date, because I was hoping that did:keri would be a little better documented. But if you'd like to do that now, I'm happy to move ahead.

I would prefer NOT to archive the repo; there are many references to the spec in docs scattered all over the place.

**Comment by dhh1128** [comment]
I opened PR #43 with a suggestion about how we could modify the spec. What do you think, @bumblefudge ?

**Comment by brianorwhatever** [comment]
Note merged, suggest closing
