### ISSUE TITLE
Proposing did:peer:4

### ISSUE THREAD

**Issue by dbluhm** [decentralized-identity/peer-did-method-spec#58]
Here is a link to a document outlining a proposed did:peer:4 method: https://hackmd.io/@dbluhm/did-peer-4
A reference implementation can be found here: https://github.com/dbluhm/did-peer-4

This method has a lot in common with its predecessors but we believe this is a cleaner, more to the point execution. Over time, our understanding of what we needed from ledger-less DIDs has evolved. My hope is that this method more closely reflects our evolved understanding.

This method can be roughly equated to a combination of did:peer:2 and did:peer:3. did:peer:2 was meant to be a "Doc in a DID." However, in the interest of keeping the identifier to a "manageable" length, there are some encoding rules to shorten values. This encoding was lossy -- verification method identifiers, for instance, cannot be expressed. This ultimately limited what kind of documents could be expressed. This also made it harder to implement.

did:peer:4 tosses out the notion of trying to shorten the identifier in the interest of keeping the method simple, easy to implement, and maximally flexible. It draws inspiration from DID methods like did:ion that has a short form and a long form of the DID. It shares the Ion characteristic of storing in the long form all the info needed to resolve a DID document. It diverges from Ion's approach in how that info is stored and how the short form is to be used.

did:peer:3 was a solution to the problem of always needing to pass the full DID Doc when using did:peer:2. The short form of did:peer:4 is intended to address this same length concern. did:peer:3, however, on it’s own, has little value. We believe it makes sense to combine the short form and long form identifiers as demonstrated with did:peer:4.

cc: @swcurran @TelegramSam

**Comment by TimoGlastra** [comment]
Could we use this instead of did:peer:3, and also name it did:peer:3? IMO it's getting a bit crazy with trying to fix did:peer and it now having 4 numalgos, and as there's no implementations yet of did:peer:3 AFAIK, we should give ourselves some time and think about how do we want to do this properly. We're not making it easier for implementers.

Following this trend we'll be at did:peer:9 by end of next year 😅

**Comment by TimoGlastra** [comment]
Or can't we create a new did method? We deprecate did:peer, as we don't need all the complex update logic, and we only support numalgo 4. The goal of the method is peer to peer, statically resolvable, simple did method.

E.g. did:peers (s for simple). Or did:static

**Comment by dhh1128** [comment]
I am sympathetic to the competing needs that Daniel and Timo highlight. I don't have a strong opinion about the best way forward, although I have a weak one that non-transferrable KERI DIDs give you what Timo is imagining (static, no KERI witnesses/infrastructure needed). The did:webs method that @swcurran has been championing includes the notion of a long and a short form of a DID, and allows arbitrary detail in the DID doc -- but solves the problem by depending on web publication infrastructure. Maybe that's not what you want here.

Anyway, one realization triggered by this GH issue is that I'm now feeling that I should remove myself from the critical path by getting some additional maintainers of did:peer. So, see issue #59.

**Comment by swcurran** [comment]
@TimoGlastra — we’re trying to get down to a single numalgo. A merge of PR was just completed (minutes ago!) to remove a lot of the ideas in the original did:peer, to minimize it to what is being or likely to be used.  Take a scan at the newly thinned [rendered spec](https://identity.foundation/peer-did-method-spec/index.html)

With `did:peer:4`, we can also deprecate numalogs 0 (not needed — did:key is fine), 1 (not needed, covered by 4), 2/3 (not needed, covered by 4), so that all is left is a “lessons learned”-based DID peer 4.

Alternatively, we can go with did:peer:2/3 and depracate just 0 and 1, but the combination is a bit awkward, hence the idea of 4 that should be the last for quite a while.

**Comment by swcurran** [comment]
@TimoGlastra, @dhh1128 and others -- we're going to be talking about did:peer:4 on the Aries Working Group call today at 7:00 Pacific / 16:00 Central Europe -- https://wiki.hyperledger.org/display/ARIES/2023-08-30+Aries+Working+Group+Call

**Comment by TelegramSam** [comment]
This is resolved with #61 merged.
